version: "3.9"
services:
  react:
    build: .
    ports:
      - "3010:3000"
    volumes:
      - .:/work
    links:
      - backend
  backend:
    build: ../backend/.
    ports:
      - "3004:3001"
